/* Consultas*/


/* SELECT FROM */
SELECT codcidade, cidade FROM CIDADE
WHERE UF = 'MG';

/* SELECT FROM */
SELECT ENDERECO,NUM, CNPJ FROM LOJA
WHERE NOME = 'SÃO JOSE';


/* SELECT FROM */
SELECT  fornecedor , endereco ,num ,bairro ,cep ,contato FROM Fornecedor
WHERE codfornecedor = 110059;


/* SELECT COUNT */
SELECT COUNT(*) AS QUANTIDADE, uf 
FROM CIDADE
GROUP BY  uf ;



/* SELECT COUNT */
SELECT COUNT(*) AS QUANTIDADE, BAIRRO
FROM LOJA
GROUP BY  BAIRRO ;

/* SELECT COUNT */
SELECT COUNT(*) AS QUANTIDADE, CEP
FROM FORNECEDOR
GROUP BY CEP;


/* VERIFICANDO AS TABELAS DO BANCO */
SELECT MIN(NUM) AS MENOR_NUM
FROM LOJA;


/* SELECT MAX */
SELECT MAX(codfornecedor) AS MAIOR_codfornecedor
FROM Fornecedor;


/* SELECT COUNT*/
SELECT COUNT(*) FROM LOJA;



/* SELECT */
SELECT NOME, ENDERECO, NUM, BAIRRO, TEL
FROM LOJA
WHERE INSC = '4848452548'
AND CNPJ = '03.293.074/0001-84'


/* SELECT */
SELECT NOME, ENDERECO, NUM, BAIRRO, TEL
FROM LOJA
WHERE INSC = '4848452548'
AND CNPJ = '03.293.074/0001-84'

